version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
      - REDIS_HOST=redis
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis

volumes:
  mongodb_data:
